version: '3.5'
services:
  database:
    image: my-postgres
    build: .
    ports:
      - 5432:5432
    environment:
      # Default user is postgres
      # Default database is postgres
      POSTGRES_PASSWORD: password
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
